### PR TITLE
removes all usage of rest_framework from router.views.py

### PR DESCRIPTION
**Pull request by lsh-0**
cc @giorgiosironi 

CI is a bit of a mess on elife-api right now. I know it's 'legacy', but the tests are failing after the security fix bumping `djangorestframework` and that library is just so much more trouble than it's worth these days.

### CODE REVIEW

**Comment by lsh-0** [comment]
for some reason the Jenkins CI thingy isn't appearing. 

results are here: https://alfred.elifesciences.org/job/pull-requests-projects/job/elife-api/job/PR-34/

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/job/pull-requests-projects/job/elife-api/view/change-requests/job/PR-34/3/console
```
Could not update commit status, please check if your scan credentials belong to a member of the organization or a collaborator of the repository and repo:status scope is selected
```
(permission problem, will solve and re-run)

**Comment by giorgiosironi** [comment]
Build now runs on PRs and is green.

**Comment by lsh-0** [comment]
thanks for that, @giorgiosironi

**Pull request merged**
