### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by lsh-0** [comment]
well @giorgiosironi , it was passing under the old Jenkins ;) 

there is another PR to go into develop, then it and these changes will have to be deployed into master. probably for the last time. I think we should look to remove `master.api.elifesciences.org` as soon as we practically can.

**Comment by gnott** [comment]
I also wasn't sure of the status of this PR, thanks for looking @lsh-0

**Comment by giorgiosironi** [comment]
The build was ported to https://ci--alfred.elifesciences.org/job/legacy-elife-api which builds the `develop` branch, testing it but not deploying to any server (as it's all on the old builder).

**Comment by lsh-0** [comment]
https://ci--alfred.elifesciences.org/job/legacy-elife-api/3/console

looks like it's passing. I'll get it deployed today

**Pull request merged**
